language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- nightly
- pypy3
matrix:
  allow_failures:
  - python: pypy3
addons:
  apt:
    packages:
    - libenchant-dev
    - aspell-en
cache:
  directories:
  - $HOME/.cache/pip
install:
- pip install pyenchant
- pip install regex
- pip install pyflakes
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install pylint
- pip install docutils
script:
- tests/run-tests --verbose
- private/run-pyflakes
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || private/run-pylint
- find -name "*.rst" | xargs -L1 -t -I{} rst2xml.py --strict {} /dev/null
- make -C doc

# vim:ts=2 sts=2 sw=2 et
